shared:
  image: centos:centos7

annotations:
  screwdriver.cd/chainPR: true

jobs:
  prjob1:
    requires: [ ~commit, ~pr ]
    steps:
      - echo: echo hoge
  prjob2:
    requires: [ prjob1 ]
    steps:
      - echo: echo hoge
  prjob3:
    requires: [ prjob1 ]
    steps:
      - echo: echo hoge
  prjob4:
    requires: [ prjob1 ]
    steps:
      - echo: echo hoge
